language: "ruby"

rvm:
  - "2.3.0"
  - "2.5.0"

sudo: false

install:
  - bundle install --retry=3

script:
  - bundle exec rspec

addons:
  code_climate:
    repo_token: 5fd7ff414c2343638963d42d48963f7acc035d5361072a56999a76e890c53124

after_success:
  - bundle exec codeclimate-test-reporter
